### ISSUE TITLE
node-tunnel failing in docker Error: Unable to establish one or more of the specified browser connections.

### ISSUE THREAD

**Issue by grantis** [LambdaTest/testcafe-browser-provider-lambdatest#6] opened 2020-02-18 07:08 UTC
Hi guys, Im using testcafe-browser-provider-lambdatest in docker node:12 and it's failing to connect. I believe node-tunnel may be the cause, hopefully you could help. 

I'm passing in the appropriate environment variables, username and key and configuration.

`NODE_ENV=qa $(npm bin)/testcafe 'lambdatest:Chrome@79.0:Windows 10' scenarios/*.scenario.js`

Error message:

```
Auth succeeded
Checking for updates
Binary already at latest version
Starting tunnel
⠼
⠴
⠼
ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
```

This issue found me when I ran it in concourse and runs fine locally. 

Thank you

**Comment by prateekLambda** [comment] 2020-02-18 08:45
Hi @grantis,
This is Prateek from LambdaTest.
Could you please share your registered email address on LambdaTest? So, we can quickly check the logs of your test.

**Comment by grantis** [comment] 2020-02-20 20:38
Hi @prateekLambda , its grant.rigby@spidertracks.co.nz . Sorry for the late response. So I setup something similar with testcafe-browser-provider-browserstack and it appears to have worked so I'm not sure what's happening here.

**Comment by prateekLambda** [comment] 2020-02-21 08:25
Hi @grantis I have just dropped you a mail for the issue you have reported.

**Comment by sduduzog** [comment] 2020-06-23 08:44
Was this resolved? I just got  the same issue with my setup

**Comment by sduduzog** [comment] 2020-06-23 08:47
Here's the bit of the logs from my setup

08:54:18   Info     |       {"status":"SUCCESS","message":"OK"}Tunnel successfully initiated. You can start testing now
09:00:08   Error    |       { Error: Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.
09:00:08   Error    |       at BrowserSet._waitConnectionsOpened (D:\Octopus\Applications\Yumbi Staging 2\yumbi-e2e\0.0.15_3\node_modules\testcafe\src\runner\browser-set.js:83:30)
09:00:08   Error    |       at Promise.resolve.then (D:\Octopus\Applications\Yumbi Staging 2\yumbi-e2e\0.0.15_3\node_modules\testcafe\src\runner\browser-set.js:106:35) code: 'E1004', data: [] }
10:03:36   Verbose  |       Process C:\Windows\system32\WindowsPowershell\v1.0\PowerShell.exe in C:\Octopus\Work\20200623065235-56094-6 exited with code -1

**Comment by prateekLambda** [comment] 2020-06-23 09:31
Hi Beautus,

Hope you are well and safe,

Thanks for the response. This is Prateek from LambdaTest. Yes we have done
the debugging of the issue which you have raised and fixed the problem.
As of now the issue you are getting mostly comes across when the parallel
tests are running more then the concurrency user has. As our testcafe
plugin is used by most of our users and the enterprises they have not
reported the issue yet. So, I want to understand the scenario of your test
suite flow. It will really helpful if we can connect over the quick screen
share and resolve this issue which you are facing and resolve the issue
quickly.

Looking forward to hearing from you.


*Prateek singh*

Automation Analyst



[image: cid:image001.png@01D3C4CF.0C5AADA0]



LambdaTest | www.lambdatest.com

UK: +44 115-888-3430 | US: +12098132758

**Comment by dubesar** [comment] 2022-01-03 05:30
This issue may be caused particularly due to docker environment and not related to testcafe plugin - Check these network docs of Docker here -

1. https://stackoverflow.com/questions/39512728/cant-connect-to-docker-container-from-outside
2. https://github.com/coreos/bugs/issues/1936
Its related to docker network.
Closing this issue now, feel free to open whenever required if not able to resolve the issue.

**Closed by dubesar** 2022-01-03 05:30 UTC
